### ISSUE TITLE
Feature: Advanced configuration

### ISSUE THREAD

**Issue by zbalkan** [zbalkan/nmap_scan#4]
# Summary
The idea is to provide flexibility to the users during scheduling.

# Usage
For instance, here's a cron configuration per vlans:
```cron
0 0 1 * *          python3 $SCANNER_PATH/nmap_scan.py -f subnets/vlan100.json
0 0 2 * *          python3 $SCANNER_PATH/nmap_scan.py -f subnets/vlan1.json
```

# TODO
- [ ] Accept subnet files under the default folder if no arguments passed
- [ ] If a subnet is passed, validate it and scan the subnet
- [ ] If a subnet file is passed, validate it and scan

**Comment by zbalkan** [comment]
In current scheme, we use systemd timers for timing and a configuration file that includes subnets. We can set up tasks but it is easier now  as subnets are scanned consecutively, therefore no need to separate the tasks.
